name: Build and Publish 4.19.1 VS Code Extension Overlay

on:
  workflow_dispatch:

jobs:
  build-vscode-extension-overlay-package:
    name: Build VS Code Extension Overlay
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Install Carvel tools
        shell: bash
        run: curl -L https://carvel.dev/install.sh | bash

      - name: Install code-server
        shell: bash
        run: |
          curl --fail -L -o code-server.tar.gz https://github.com/coder/code-server/releases/download/v4.19.1/code-server-4.19.1-linux-amd64.tar.gz
          mkdir code-server
          tar -C code-server --strip-components 1 -xvf code-server.tar.gz

      - name: Install VS Code extensions
        shell: bash
        run: |
          ./code-server/bin/code-server --install-extension vscjava.vscode-java-pack@0.25.15
          # downgrade the redhat java extension, even though we specify a "pack" version above, it pulls in latest
          # temporarily comment out and see if no longer needed since now using newer version of code-server
          # ./code-server/bin/code-server --install-extension redhat.java@1.24.0
          # install the Tanzu Developer Tools extension
          export TANZU_DEV_TOOLS_VERSION="1.4.0"
          curl -o vmware.tanzu-dev-tools.vsix "https://vmware.gallery.vsassets.io/_apis/public/gallery/publisher/vmware/extension/tanzu-dev-tools/${TANZU_DEV_TOOLS_VERSION}/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage"
          ./code-server/bin/code-server --install-extension vmware.tanzu-dev-tools.vsix

          export TANZU_ACCELERATOR_VERSION="1.0.5"
          # install the Tanzu App Accelerator extension
          curl -o vmware.tanzu-app-accelerator.vsix "https://vmware.gallery.vsassets.io/_apis/public/gallery/publisher/vmware/extension/tanzu-app-accelerator/${TANZU_ACCELERATOR_VERSION}/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage"
          ./code-server/bin/code-server --install-extension vmware.tanzu-app-accelerator.vsix

          rm -f $HOME/.local/share/code-server/extensions/extensions.json

      - name: Publish VS Code extensions as files
        shell: bash
        run: |
          REPOSITORY_OWNER=${{github.repository_owner}}
          imgpkg push \
            -i ghcr.io/${REPOSITORY_OWNER,,}/vscode-java-extensions-files:4.19.1-1.0.0 \
            -f $HOME/.local/share/code-server/extensions \
            --registry-username=${{github.actor}} \
            --registry-password=${{secrets.GITHUB_TOKEN}}

      - name: Publish VS Code extensions as tarball
        shell: bash
        run: |
          REPOSITORY_OWNER=${{github.repository_owner}}
          mkdir /tmp/files
          cd $HOME/.local/share/code-server/extensions
          tar cvfz /tmp/files/extensions.tar.gz .
          imgpkg push \
            -i ghcr.io/${REPOSITORY_OWNER,,}/vscode-java-extensions-tar:4.19.1-1.0.0 \
            -f /tmp/files \
            --registry-username=${{github.actor}} \
            --registry-password=${{secrets.GITHUB_TOKEN}}
