name: Build and Publish 2.0.12 Code Server Overlay

on:
  workflow_dispatch:

jobs:
  build-code-server-overlay-package:
    name: Build Code Server Overlay
    runs-on: ubuntu-latest

    steps:
      - name: check out the repository
        uses: actions/checkout@v3

      - name: install carvel tools
        shell: bash
        run: curl -L https://carvel.dev/install.sh | bash

      - name: install code-server
        shell: bash
        run: |
          sudo mkdir /opt/editor
          cd /tmp
          curl --fail -L -o code-server.tar.gz https://github.com/coder/code-server/releases/download/v4.10.1/code-server-4.10.1-linux-amd64.tar.gz
          sudo tar -C /opt/editor --strip-components 1 -xvf code-server.tar.gz

          # work around imgpkg not being able to handle soft links
          sudo rm /opt/editor/lib/vscode/bin/helpers/browser.sh
          sudo cp /opt/editor/lib/vscode/bin/helpers/browser-linux.sh /opt/editor/lib/vscode/bin/helpers/browser.sh
          sudo rm /opt/editor/lib/vscode/bin/remote-cli/code-server
          sudo cp /opt/editor/lib/vscode/bin/remote-cli/code-linux.sh /opt/editor/lib/vscode/bin/remote-cli/code-server
          rm code-server.tar.gz

      - name: publish code server
        shell: bash
        run: |
          REPOSITORY_OWNER=${{github.repository_owner}}
          sudo imgpkg push \
            -i ghcr.io/${REPOSITORY_OWNER,,}/code-server-and-extensions-files:2.0.12 \
            -f /opt/editor \
            --registry-username=${{github.actor}} \
            --registry-password=${{secrets.GITHUB_TOKEN}}
